# sudo: false --> run dist image in docker container on shared host for faster startup (runs slower)
# sudo: required --> run dist image in VM on Google Compute Engine for slower startup (runs faster)
#sudo: required
#dist: trusty

language: java # v1.8.0_151 (Oracle), trusty ubuntu 14.04
install:
        - java -version
        # Install the Android SDK Dependency.
        - export ANDROID_HOME=/opt/android-sdk-linux
        - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip && unzip -q android-sdk-tools.zip -d ${ANDROID_HOME} && rm android-sdk-tools.zip
        - PATH=${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${PATH}
        # Silence warning.
        - mkdir -p ~/.android && touch ~/.android/repositories.cfg
        # Accept licenses before installing components, no need to echo y for each component
        - yes | sdkmanager --licenses
        # Platform tools
        - sdkmanager "emulator" "tools" "platform-tools" > /dev/null

        # install pre-compiled flutter
        - FLUTTER_CHANNEL=stable
        - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL}
        - sdkmanager "platforms;android-28" "build-tools;28.0.3" > /dev/null
        - sdkmanager --list | head -15
        - sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
        - wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz > /dev/null && rm flutter.tar.xz
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor -v

script:
  - cd flutter_app
  - flutter build apk
  - ls -latr ~/.gradle/caches
  - du -hs ~/.gradle/caches/journal-1
  - du -hs ~/.gradle/caches/modules-2
  - du -hs ~/.gradle/caches/jars-3
  - du -hs ~/.gradle/caches/transforms-1
  - du -hs ~/.gradle/caches/*.*.*
before_cache:
  # clean cache
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#  - rm -rf ~/.gradle/caches/*.*.*
  - find $HOME/.gradle/caches/modules-2 -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.gradle/caches/modules-2
#    - $HOME/.gradle/caches
#    - $HOME/.gradle/wrapper/
    - $HOME/.pub-cache
#    - $PWD/flutter_app/android/.gradle